//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPropietaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidatos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public string PuestoAspirante { get; set; }
        public string Deparamento { get; set; }
        public double SalarioDeseado { get; set; }
        public string Competencias { get; set; }
        public string Capacitaciones { get; set; }
        public string Experiencia { get; set; }
        public string Recomendacion { get; set; }
    }
}
