//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPropietaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaLaboral
    {
        public string Empresa { get; set; }
        public string Puesto { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinalizacion { get; set; }
    }
}
