//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPropietaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puestos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string NivelRiesgo { get; set; }
        public double SalarioMinimo { get; set; }
        public double SalarioMaximo { get; set; }
        public string Departamento { get; set; }
        public bool Estado { get; set; }
    }
}
